# Start from the Nginx image based on Alpine Linux
FROM nginx:alpine

# Set the maintainer label to identify who made this Dockerfile
LABEL maintainer="youremail@example.com"

# Remove the default nginx index page
RUN rm -rf /usr/share/nginx/html/*

# Copy the HTML project folder to the default nginx serving directory
COPY .  /usr/share/nginx/html

# Ensure permissions are set correctly
RUN chmod -R 755 /usr/share/nginx/html

# Expose port 8080
EXPOSE 8000

# Customize the Nginx configuration to listen on port 8080 instead of the default port 80
RUN sed -i 's/listen\(.*\)80;/listen 8000;/' /etc/nginx/conf.d/default.conf

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
